### ISSUE TITLE
Support taking screenshots

### ISSUE THREAD

**Issue by mborgerson** [mborgerson/nxdk-rdt#7]

**Comment by JayFoxRox** [comment]
Some reasoning for why we need this as a seperate command:

If we just call a kernel function to get the current video address, then retrieve the result on a PC and send a new command for the memory fetch the game might already flipped buffers again.

This shouldn't have a priority though as this will mostly be interesting if we have the ability to run NXDK-RDT in the background while another process might switch video addresses.
Currently this is impossible though. So we can manually do the following steps as timing is not an issue (if we run in the background we'll need an atomic operation):

* Get framebuffer addresses
* Optional: Wait for vblank
* Optional: Capture video output surface contents
* Optional: Capture GPU color surface contents
* Optional: Capture GPU depth surface contents

---

An alternative approach is uploading custom code which does the atomic operation. See #6 .

**Comment by JayFoxRox** [comment]
Update on this:

```python
	base = 0xFD000000
	def crtc_read(i):
		write_u8(base + 0x6013D4, i)
		return read_u8(base + 0x6013D5)
	pitch = crtc_read(0x13)
	pitch |= (crtc_read(0x19) & 0xE0) << 3
	pitch |= (crtc_read(0x25) & 0x20) << 6
	pitch *= 8 #FIXME: Why do I need to do this?
	bytes_per_pixel = crtc_read(0x28) & 0x7F #FIXME: 3 when it's actually 4..
	is_565 = False if bytes_per_pixel != 2 else (read_u32(base + 0x680600) & 0x1000) > 0 #FIXME: Untested
	framebuffer_addr = 0x80000000 | read_u32(base + 0x600800)
	print("fb: " + format(framebuffer_addr, '08X'))
	print("pitch: " + str(pitch))
	print("565: " + str(is_565))
	print("bytes_per_pixel: " + str(bytes_per_pixel))

	#FIXME: How to get these? VGA timing foo?
	width = 640
	height = 480

	framebuffer_data = read(framebuffer_addr, pitch * height)

	screenshot = Image.new('RGB', (width, height))
	pixels = screenshot.load()
	for y in range (0,height):
		for x in range (0,width):
			p = y * pitch + x * 4
			r = framebuffer_data[p + 0]
			g = framebuffer_data[p + 1]
			b = framebuffer_data[p + 2]
			pixels[x, y]=(r,g,b)

	screenshot.save("screenshot.png")
```

This works, BUT it currently only supports X8R8G8B8 (and probably colors wrong) and it needs manual setting of width and height.
It's also a lot of magic numbers.. not nice

Ideally retrieving the VGA information should be seperate from downloading images.
We should add support for various formats so we can just download or upload surfaces to the Xbox.
I'm personally more interested in downloading offscreen surfaces in memory than downloading the VGA portion

Also due to protobuf or lwip issues this will not be able to transfer a full screenshot. I've only tested transferring the first 50 rows or something (in 100 or 200 byte chunks). Going higher will cause nxdk-rdt to say "ERROR: Null request" and I'm unable to reconnect. Similarily receiving the entire screenshot in one packet is impossible because the nxdk or protobuf network implementation chokes on packets larger than ~200 bytes.
Also after a given number of bytes / packets or whatever have been send lwip will reliably crash, so this is a PITA to debug / work on.

**Comment by JayFoxRox** [comment]
Update: I've moved this into https://github.com/JayFoxRox/xbox-tools/tree/master/python-scripts .
(which will use nxdk-rdt internally in the future. It already supports some other backends)

My focus will be on making nxdk-rdt more stable and easier to use (as a way to do low-level tasks). I won't be extending it feature wise so if you still want screenshot functionality as part of nxdk-rdt someone else has to step up.

**Comment by mborgerson** [comment]
I think it makes sense to use nxdk-rdt as an OSS backend that can be swapped out for GDB/XBDM as necessary. Nice work!
